package gov.anzong.androidnga.common.util;

/**
 * Created by Justwen on 2018/6/8.
 */
public class EmoticonUtils {

    public static final String[][] EMOTICON_LABEL = {
            {"recently", "最近"},
            {"ac", "AC娘"},
            {"a2", "新版AC娘"},
            {"ng", "NG娘"},
            {"pg", "企鹅"},
            {"pst", "潘斯特"},
            {"dt", "外域三人组"},
    };

    final static String PRR_EMOTION_URL = "https://img4.nga.178.com/ngabbs/post/smile/";

    public static String[][][] EMOTICON_URL = {
            {
            },
            {
                    {"ac", "blink", "ac0.png"},
                    {"ac", "goodjob", "ac1.png"},
                    {"ac", "上", "ac2.png"},
                    {"ac", "中枪", "ac3.png"},
                    {"ac", "偷笑", "ac4.png"},
                    {"ac", "冷", "ac5.png"},
                    {"ac", "凌乱", "ac6.png"},
                    {"ac", "吓", "ac8.png"},
                    {"ac", "吻", "ac9.png"},
                    {"ac", "呆", "ac10.png"},
                    {"ac", "咦", "ac11.png"},
                    {"ac", "哦", "ac12.png"},
                    {"ac", "哭", "ac13.png"},
                    {"ac", "哭1", "ac14.png"},
                    {"ac", "哭笑", "ac15.png"},
                    {"ac", "喘", "ac17.png"},
                    {"ac", "心", "ac23.png"},
                    {"ac", "囧", "ac21.png"},
                    {"ac", "晕", "ac33.png"},
                    {"ac", "汗", "ac34.png"},
                    {"ac", "瞎", "ac35.png"},
                    {"ac", "羞", "ac36.png"},
                    {"ac", "羡慕", "ac37.png"},
                    {"ac", "委屈", "ac22.png"},
                    {"ac", "忧伤", "ac24.png"},
                    {"ac", "怒", "ac25.png"},
                    {"ac", "怕", "ac26.png"},
                    {"ac", "惊", "ac27.png"},
                    {"ac", "愁", "ac28.png"},
                    {"ac", "抓狂", "ac29.png"},
                    {"ac", "哼", "ac16.png"},
                    {"ac", "喷", "ac18.png"},
                    {"ac", "嘲笑", "ac19.png"},
                    {"ac", "嘲笑1", "ac20.png"},
                    {"ac", "抠鼻", "ac30.png"},
                    {"ac", "无语", "ac32.png"},
                    {"ac", "衰", "ac40.png"},
                    {"ac", "黑枪", "ac44.png"},
                    {"ac", "花痴", "ac38.png"},
                    {"ac", "闪光", "ac43.png"},
                    {"ac", "擦汗", "ac31.png"},
                    {"ac", "茶", "ac39.png"},
                    {"ac", "计划通", "ac41.png"},
                    {"ac", "反对", "ac7.png"},
                    {"ac", "赞同", "ac42.png"}
            },
            //论坛新版AC娘
            {
                    {"a2", "goodjob", "a2_02.png"},
                    {"a2", "诶嘿", "a2_05.png"},
                    {"a2", "偷笑", "a2_03.png"},
                    {"a2", "怒", "a2_04.png"},
                    {"a2", "笑", "a2_07.png"},
                    {"a2", "那个…", "a2_08.png"},
                    {"a2", "哦嗬嗬嗬", "a2_09.png"},
                    {"a2", "舔", "a2_10.png"},
                    {"a2", "鬼脸", "a2_14.png"},
                    {"a2", "冷", "a2_16.png"},
                    {"a2", "大哭", "a2_15.png"},
                    {"a2", "哭", "a2_17.png"},
                    {"a2", "恨", "a2_21.png"},
                    {"a2", "中枪", "a2_23.png"},
                    {"a2", "囧", "a2_24.png"},
                    {"a2", "你看看你", "a2_25.png"},
                    {"a2", "doge", "a2_27.png"},
                    {"a2", "自戳双目", "a2_28.png"},
                    {"a2", "偷吃", "a2_30.png"},
                    {"a2", "冷笑", "a2_31.png"},
                    {"a2", "壁咚", "a2_32.png"},
                    {"a2", "不活了", "a2_33.png"},
                    {"a2", "不明觉厉", "a2_36.png"},
                    {"a2", "是在下输了", "a2_51.png"},
                    {"a2", "你为猴这么", "a2_53.png"},
                    {"a2", "干杯", "a2_54.png"},
                    {"a2", "干杯2", "a2_55.png"},
                    {"a2", "异议", "a2_47.png"},
                    {"a2", "认真", "a2_48.png"},
                    {"a2", "你已经死了", "a2_45.png"},
                    {"a2", "你这种人…", "a2_49.png"},
                    {"a2", "妮可妮可妮", "a2_18.png"},
                    {"a2", "惊", "a2_19.png"},
                    {"a2", "抢镜头", "a2_52.png"},
                    {"a2", "yes", "a2_26.png"},
                    {"a2", "有何贵干", "a2_11.png"},
                    {"a2", "病娇", "a2_12.png"},
                    {"a2", "lucky", "a2_13.png"},
                    {"a2", "poi", "a2_20.png"},
                    {"a2", "囧2", "a2_22.png"},
                    {"a2", "威吓", "a2_42.png"},
                    {"a2", "jojo立", "a2_37.png"},
                    {"a2", "jojo立2", "a2_38.png"},
                    {"a2", "jojo立3", "a2_39.png"},
                    {"a2", "jojo立4", "a2_41.png"},
                    {"a2", "jojo立5", "a2_40.png"},
            },
            //NG娘
            {
                    {"ng", "呲牙笑", "ng_1.png"},
                    {"ng", "奸笑", "ng_2.png"},
                    {"ng", "问号", "ng_3.png"},
                    {"ng", "茶", "ng_4.png"},
                    {"ng", "笑指", "ng_5.png"},
                    {"ng", "燃尽", "ng_6.png"},
                    {"ng", "晕", "ng_7.png"},
                    {"ng", "扇笑", "ng_8.png"},
                    {"ng", "寄", "ng_9.png"},
                    {"ng", "别急", "ng_10.png"},
                    {"ng", "doge", "ng_11.png"},
                    {"ng", "丧", "ng_12.png"},
                    {"ng", "汗", "ng_13.png"},
                    {"ng", "叹气", "ng_15.png"},
                    {"ng", "吃饼", "ng_16.png"},
                    {"ng", "吃瓜", "ng_17.png"},
                    {"ng", "吐舌", "ng_18.png"},
                    {"ng", "哭", "ng_19.png"},
                    {"ng", "喘", "ng_20.png"},
                    {"ng", "心", "ng_21.png"},
                    {"ng", "喷", "ng_22.png"},
                    {"ng", "困", "ng_24.png"},
                    {"ng", "大哭", "ng_25.png"},
                    {"ng", "大惊", "ng_26.png"},
                    {"ng", "害怕", "ng_27.png"},
                    {"ng", "惊", "ng_28.png"},
                    {"ng", "暴怒", "ng_30.png"},
                    {"ng", "气愤", "ng_31.png"},
                    {"ng", "热", "ng_32.png"},
                    {"ng", "瓜不熟", "ng_33.png"},
                    {"ng", "瞎", "ng_34.png"},
                    {"ng", "色", "ng_35.png"},
                    {"ng", "斜眼", "ng_37.png"},
                    {"ng", "问号大", "ng_38.png"},
            },
            //企鹅
            {
                    {"pg", "战斗力", "pg01.png"},
                    {"pg", "哈啤", "pg02.png"},
                    {"pg", "满分", "pg03.png"},
                    {"pg", "衰", "pg04.png"},
                    {"pg", "拒绝", "pg05.png"},
                    {"pg", "心", "pg06.png"},
                    {"pg", "严肃", "pg07.png"},
                    {"pg", "吃瓜", "pg08.png"},
                    {"pg", "嘣", "pg09.png"},
                    {"pg", "嘣2", "pg10.png"},
                    {"pg", "冻", "pg11.png"},
                    {"pg", "谢", "pg12.png"},
                    {"pg", "哭", "pg13.png"},
                    {"pg", "响指", "pg14.png"},
                    {"pg", "转身", "pg15.png"},
            },
            //潘斯特
            {
                    {"pst", "举手", "pt00.png"},
                    {"pst", "亲", "pt01.png"},
                    {"pst", "偷笑", "pt02.png"},
                    {"pst", "偷笑2", "pt03.png"},
                    {"pst", "偷笑3", "pt04.png"},
                    {"pst", "傻眼", "pt05.png"},
                    {"pst", "傻眼2", "pt06.png"},
                    {"pst", "兔子", "pt07.png"},
                    {"pst", "发光", "pt08.png"},
                    {"pst", "呆", "pt09.png"},
                    {"pst", "呆2", "pt10.png"},
                    {"pst", "呆3", "pt11.png"},
                    {"pst", "呕", "pt12.png"},
                    {"pst", "呵欠", "pt13.png"},
                    {"pst", "哭", "pt14.png"},
                    {"pst", "哭2", "pt15.png"},
                    {"pst", "哭3", "pt16.png"},
                    {"pst", "嘲笑", "pt17.png"},
                    {"pst", "基", "pt18.png"},
                    {"pst", "宅", "pt19.png"},
                    {"pst", "安慰", "pt20.png"},
                    {"pst", "幸福", "pt21.png"},
                    {"pst", "开心", "pt22.png"},
                    {"pst", "开心2", "pt23.png"},
                    {"pst", "开心3", "pt24.png"},
                    {"pst", "怀疑", "pt25.png"},
                    {"pst", "怒", "pt26.png"},
                    {"pst", "怒2", "pt27.png"},
                    {"pst", "怨", "pt28.png"},
                    {"pst", "惊吓", "pt29.png"},
                    {"pst", "惊吓2", "pt30.png"},
                    {"pst", "惊呆", "pt31.png"},
                    {"pst", "惊呆2", "pt32.png"},
                    {"pst", "惊呆3", "pt33.png"},
                    {"pst", "惨", "pt34.png"},
                    {"pst", "斜眼", "pt35.png"},
                    {"pst", "晕", "pt36.png"},
                    {"pst", "汗", "pt37.png"},
                    {"pst", "泪", "pt38.png"},
                    {"pst", "泪2", "pt39.png"},
                    {"pst", "泪3", "pt40.png"},
                    {"pst", "泪4", "pt41.png"},
                    {"pst", "满足", "pt42.png"},
                    {"pst", "满足2", "pt43.png"},
                    {"pst", "火星", "pt44.png"},
                    {"pst", "牙疼", "pt45.png"},
                    {"pst", "电击", "pt46.png"},
                    {"pst", "看戏", "pt47.png"},
                    {"pst", "眼袋", "pt48.png"},
                    {"pst", "眼镜", "pt49.png"},
                    {"pst", "笑而不语", "pt50.png"},
                    {"pst", "紧张", "pt51.png"},
                    {"pst", "美味", "pt52.png"},
                    {"pst", "背", "pt53.png"},
                    {"pst", "脸红", "pt54.png"},
                    {"pst", "脸红2", "pt55.png"},
                    {"pst", "腐", "pt56.png"},
                    {"pst", "星星眼", "pt57.png"},
                    {"pst", "谢", "pt58.png"},
                    {"pst", "醉", "pt59.png"},
                    {"pst", "闷", "pt60.png"},
                    {"pst", "闷2", "pt61.png"},
                    {"pst", "音乐", "pt62.png"},
                    {"pst", "黑脸", "pt63.png"},
                    {"pst", "鼻血", "pt64.png"},
            },//yixia dt 外域三人组
            {
                    {"dt", "ROLL", "dt01.png"},
                    {"dt", "上", "dt02.png"},
                    {"dt", "傲娇", "dt03.png"},
                    {"dt", "叉出去", "dt04.png"},
                    {"dt", "发光", "dt05.png"},
                    {"dt", "呵欠", "dt06.png"},
                    {"dt", "哭", "dt07.png"},
                    {"dt", "啃古头", "dt08.png"},
                    {"dt", "嘲笑", "dt09.png"},
                    {"dt", "心", "dt10.png"},
                    {"dt", "怒", "dt11.png"},
                    {"dt", "怒2", "dt12.png"},
                    {"dt", "怨", "dt13.png"},
                    {"dt", "惊", "dt14.png"},
                    {"dt", "惊2", "dt15.png"},
                    {"dt", "无语", "dt16.png"},
                    {"dt", "星星眼", "dt17.png"},
                    {"dt", "星星眼2", "dt18.png"},
                    {"dt", "晕", "dt19.png"},
                    {"dt", "注意", "dt20.png"},
                    {"dt", "注意2", "dt21.png"},
                    {"dt", "泪", "dt22.png"},
                    {"dt", "泪2", "dt23.png"},
                    {"dt", "烧", "dt24.png"},
                    {"dt", "笑", "dt25.png"},
                    {"dt", "笑2", "dt26.png"},
                    {"dt", "笑3", "dt27.png"},
                    {"dt", "脸红", "dt28.png"},
                    {"dt", "药", "dt29.png"},
                    {"dt", "衰", "dt30.png"},
                    {"dt", "鄙视", "dt31.png"},
                    {"dt", "闲", "dt32.png"},
                    {"dt", "黑脸", "dt33.png"}
            },
    };

    public static String getPathByURI(String uri) {
        for (int category = 0; category < EMOTICON_URL.length; category++) {
            for (int index = 0; index < EMOTICON_URL[category].length; index++) {
                if (EMOTICON_URL[category][index][1].equals(uri)) {
                    return getFilePath(category, index);
                }
            }
        }
        return null;
    }

    private static String getFilePath(int category, int position) {
        String name = EMOTICON_URL[category][position][2];
        return EMOTICON_URL[category][position][0] + "/" + name;
    }
}
