package gov.anzong.androidnga.common.util;

import org.apache.commons.io.FilenameUtils;

/**
 * Created by Justwen on 2018/6/8.
 */
public class EmoticonUtils {

    public static final String[][] EMOTICON_LABEL = {
            {"ac", "AC娘"},
            {"a2", "新版AC娘"},
            {"ng", "NG娘"},
            {"pg", "企鹅"},
            {"pst", "潘斯特"},
            {"dt", "外域三人组"},
    };


    public static final String[][] EMOTICON_URL = {
            {
                    "https://img4.nga.178.com/ngabbs/post/smile/ac0.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/ac1.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/ac2.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/ac3.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/ac4.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/ac5.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/ac6.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/ac7.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/ac8.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/ac9.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/ac10.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/ac11.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/ac12.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/ac13.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/ac14.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/ac15.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/ac16.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/ac17.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/ac18.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/ac19.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/ac20.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/ac21.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/ac22.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/ac23.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/ac24.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/ac25.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/ac26.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/ac27.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/ac28.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/ac29.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/ac30.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/ac31.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/ac32.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/ac33.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/ac34.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/ac35.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/ac36.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/ac37.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/ac38.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/ac39.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/ac40.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/ac41.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/ac42.png",
            },
            //论坛新版AC娘
            {
                    "https://img4.nga.178.com/ngabbs/post/smile/a2_05.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/a2_05.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/a2_03.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/a2_04.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/a2_07.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/a2_08.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/a2_09.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/a2_10.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/a2_14.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/a2_16.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/a2_15.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/a2_17.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/a2_21.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/a2_23.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/a2_24.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/a2_25.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/a2_27.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/a2_28.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/a2_30.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/a2_31.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/a2_32.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/a2_33.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/a2_36.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/a2_51.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/a2_53.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/a2_54.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/a2_55.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/a2_47.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/a2_48.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/a2_45.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/a2_49.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/a2_18.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/a2_19.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/a2_52.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/a2_26.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/a2_11.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/a2_12.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/a2_13.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/a2_20.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/a2_22.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/a2_42.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/a2_37.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/a2_38.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/a2_39.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/a2_41.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/a2_40.png",
            },
            //NG娘
            {
                    "https://img4.nga.178.com/ngabbs/post/smile/ng_1.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/ng_2.png",//阿尼亚
                    "https://img4.nga.178.com/ngabbs/post/smile/ng_3.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/ng_4.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/ng_5.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/ng_6.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/ng_7.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/ng_8.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/ng_9.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/ng_10.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/ng_11.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/ng_12.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/ng_13.png",
                    //"https://img4.nga.178.com/ngabbs/post/smile/ng_14.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/ng_15.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/ng_16.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/ng_17.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/ng_18.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/ng_19.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/ng_20.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/ng_21.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/ng_22.png",
                    //"https://img4.nga.178.com/ngabbs/post/smile/ng_23.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/ng_24.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/ng_25.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/ng_26.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/ng_27.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/ng_28.png",
                    //"https://img4.nga.178.com/ngabbs/post/smile/ng_29.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/ng_30.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/ng_31.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/ng_32.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/ng_33.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/ng_34.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/ng_35.png",
                    //"https://img4.nga.178.com/ngabbs/post/smile/ng_36.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/ng_37.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/ng_38.png"
            },
            {
                    "https://img4.nga.178.com/ngabbs/post/smile/pg01.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/pg02.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/pg03.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/pg04.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/pg05.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/pg06.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/pg07.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/pg08.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/pg09.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/pg10.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/pg11.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/pg12.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/pg13.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/pg14.png",
                    "https://img4.nga.178.com/ngabbs/post/smile/pg15.png",
            },
            {
                    "http://img4.nga.178.com/ngabbs/post/smile/pt00.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/pt01.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/pt02.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/pt03.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/pt04.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/pt05.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/pt06.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/pt07.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/pt08.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/pt09.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/pt10.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/pt11.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/pt12.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/pt13.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/pt14.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/pt15.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/pt16.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/pt17.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/pt18.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/pt19.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/pt20.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/pt21.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/pt22.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/pt23.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/pt24.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/pt25.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/pt26.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/pt27.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/pt28.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/pt29.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/pt30.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/pt31.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/pt32.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/pt33.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/pt34.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/pt35.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/pt36.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/pt37.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/pt38.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/pt39.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/pt40.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/pt41.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/pt42.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/pt43.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/pt44.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/pt45.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/pt46.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/pt47.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/pt48.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/pt49.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/pt50.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/pt51.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/pt52.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/pt53.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/pt54.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/pt55.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/pt56.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/pt57.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/pt58.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/pt59.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/pt60.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/pt61.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/pt62.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/pt63.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/pt64.png",
            },//yixia dt 外域三人组
            {
                    "http://img4.nga.178.com/ngabbs/post/smile/dt01.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/dt02.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/dt03.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/dt04.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/dt05.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/dt06.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/dt07.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/dt08.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/dt09.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/dt10.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/dt11.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/dt12.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/dt13.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/dt14.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/dt15.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/dt16.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/dt17.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/dt18.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/dt19.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/dt20.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/dt21.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/dt22.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/dt23.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/dt24.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/dt25.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/dt26.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/dt27.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/dt28.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/dt29.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/dt30.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/dt31.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/dt32.png",
                    "http://img4.nga.178.com/ngabbs/post/smile/dt33.png",},
    };

    public static String getPathByURI(String uri) {
        for (int category = 0; category < EMOTICON_URL.length; category++) {
            for (int index = 0; index < EMOTICON_URL[category].length; index++) {
                if (EMOTICON_URL[category][index].equals(uri)) {
                    return getFilePath(category, index);
                }
            }
        }
        return null;
    }

    private static String getFilePath(int category, int position) {
        String httpUri = EMOTICON_URL[category][position];
        return EMOTICON_LABEL[category][0] + "/" + FilenameUtils.getName(httpUri);
    }
}
